openapi: '3.0.2'
info:
  title: glyph-api
  version: '1.0'
  description: 'Rest API to obtain a random string based on an input text and a simple configuration'
servers:
  - url: https://api.glyph.rat.la/v1
    description: Production server
  - url: http://api.glyph.localhost:8081/v1
    description: Local development server

paths:
  /healthcheck:
    get:
      description: 'App liveness prove'
      parameters: []
      responses:
        '200':
          description: 'The app is working'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
              example:
                $ref: doc/examples/healthcheck-body.json
            text/plain:
              schema:
                type: string
              example: OK

components:
  schemas:
    Status:
      properties:
        status:
          type: string
